version: "3"

services:
  db:
    image: postgres:12.2-alpine
    container_name: "database"
    ports:
      - "49153:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresql/data

  web:
    build: .
    container_name: "shopping-list"
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_NAME: "postgres"
      DB_HOST: "db"
      DB_PORT: "5432"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge
